services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hr_system
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
  app:
    build: .
    container_name: hr-system
    privileged: true
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2g
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    name: app-network